language: go
sudo: false
os:
#  - linux
 - windows
go:
#  - 1.10.x
 - 1.x
#  - tip
go_import_path: pack.ag/amqp
matrix:
 include:
  - go: 1.x
    os: linux
    env: COVERAGE=1
 allow_failures:
  - go: tip
before_install:
  - if [ -n "$COVERAGE" ]; then go get -v github.com/mattn/goveralls  ; fi
  - if [ -n "$COVERAGE" ]; then go get -v golang.org/x/tools/cmd/cover; fi
  - go get -t -v -d -tags "integration gofuzz" ./...
script:
  - make ci
  - if [ -n "$COVERAGE" ]; then goveralls -coverprofile=cover.out -service=travis-ci; fi
