language: go
sudo: false
os:
#  - linux
 - windows
go:
#  - 1.10.x
 - 1.x
#  - tip
go_import_path: pack.ag/amqp
matrix:
 allow_failures:
  - go: tip
before_install:
  - echo $TRAVIS_GO_VERSION
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get -v github.com/mattn/goveralls  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get -v golang.org/x/tools/cmd/cover; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
  - go get -t -v -d -tags "integration gofuzz" ./...
script:
  - make ci
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then goveralls -coverprofile=cover.out -service=travis-ci; fi
